import json
a = '''{
    "": "ekGQEoM238DcHQ8O8TPz0ZK1Irke6CpzSNbSaDF4vxBUoX7IHkwJzRMUA9DZwfTY",
    "id_aboutForm-icon": "C:/fakepath/sign_v6_.png",
    "id_aboutForm-logo": "C:/fakepath/sign_v6_.png",
    "id_aboutForm-name": "Priyanshu Mishra",
    "id_aboutForm-about": "I am a student at Symbiosis Institute of Computer Studies and Research",
    "id_aboutForm-work_title": "Artist",
    "id_aboutForm-work_desc": "Welcome to my website! My name is Priyanshu Mishra, and I am a professional in Artist. I have 2 of experience in Visual Effects and have helped many individuals and companies achieve their goals. Please scroll down to know more about me! ",
    "id_aboutForm-experience_years": "2",
    "id_aboutForm-skill_1_title": "Technical Skills",
    "id_aboutForm-skill_1_desc": " I am proficient in programming languages, graphic design software, or project management tools.",
    "id_aboutForm-skill_2_title": "Creative Skills",
    "id_aboutForm-skill_2_desc": "I have this ability to think outside the box and come up with innovative ideas.",
    "id_aboutForm-skill_3_title": "Analytical Skills",
    "id_aboutForm-skill_3_desc": "Some of my analytical skills are crucial in industries such as finance, data analytics, and research.",
    "id_aboutForm-skill_4_title": "Soft Skills",
    "id_aboutForm-skill_4_desc": "My soft skills include communication, teamwork, leadership, problem-solving, and time management",
    "id_aboutForm-talent_1_title": "Artistic Talent",
    "id_aboutForm-talent_1_perc": "99",
    "id_aboutForm-talent_2_title": "Technical Talent",
    "id_aboutForm-talent_2_perc": "80",
    "id_aboutForm-talent_3_title": "Athletic Talent",
    "id_aboutForm-talent_3_perc": "60",
    "id_aboutForm-age": "21",
    "id_aboutForm-insta_ID": "https://www.instagram.com/",
    "id_eventForm-TOTAL_FORMS": "5",
    "id_eventForm-INITIAL_FORMS": "0",
    "id_eventForm-MIN_NUM_FORMS": "0",
    "id_eventForm-MAX_NUM_FORMS": "1000",
    "id_eventForm-0-date": "2001-02-03",
    "id_eventForm-0-event_title": "I had just been born",
    "id_eventForm-0-desc_1": "I was born in Bokaro, Jharkhand.",
    "id_eventForm-0-desc_2": "I currently live in Pune, Maharashtra.",
    "id_eventForm-1-date": "2018-12-23",
    "id_eventForm-1-event_title": "I Passed my 10th",
    "id_eventForm-1-desc_1": "I made a Drone as a IoT Project in the final year.",
    "id_eventForm-1-desc_2": "I learned languages like Java and HTML",
    "id_eventForm-2-date": "2020-06-12",
    "id_eventForm-2-event_title": "Completed my High School Studies",
    "id_eventForm-2-desc_1": "My subjects were: Physics, Chemistry, Maths and Computers",
    "id_eventForm-2-desc_2": "I also got First prize in Drawing Competitions.",
    "id_eventForm-3-date": "2021-02-21",
    "id_eventForm-3-event_title": "Got into SICSR",
    "id_eventForm-3-desc_1": "Made various projects including this website.",
    "id_eventForm-3-desc_2": "Got internship at Drexfall",
    "id_eventForm-4-date": "2024-02-23",
    "id_eventForm-4-event_title": "Will graduate from collage",
    "id_eventForm-4-desc_1": "Graduation will be finished",
    "id_eventForm-4-desc_2": "Also complete my itnernships.",
    "id_portForm-TOTAL_FORMS": "5",
    "id_portForm-INITIAL_FORMS": "0",
    "id_portForm-MIN_NUM_FORMS": "0",
    "id_portForm-MAX_NUM_FORMS": "1000",
    "id_portForm-0-image": "C:/fakepath/car2.png",
    "id_portForm-0-image_desc": "Creative Ideas",
    "id_portForm-0-item_title": "Sketch",
    "id_portForm-0-desc": "A 3d model of my sketch made and rendered in Blender.",
    "id_portForm-1-image": "C:/fakepath/sig2.png",
    "id_portForm-1-image_desc": "Personal Work",
    "id_portForm-1-item_title": "Signature",
    "id_portForm-1-desc": "A 3d model of my signature made and rendered in Blender",
    "id_portForm-2-image": "C:/fakepath/sketch5.png",
    "id_portForm-2-image_desc": "Blender Practice ",
    "id_portForm-2-item_title": "Concept Car",
    "id_portForm-2-desc": "A 3d model of my concept car made and rendered in Blender.",
    "id_portForm-3-image": "C:/fakepath/phupwlp.png",
    "id_portForm-3-image_desc": "Abstract Art",
    "id_portForm-3-item_title": "Mandelbrot Set",
    "id_portForm-3-desc": "A 3d model of my Mandelbrot Set made and rendered in Blender.",
    "id_portForm-4-image": "C:/fakepath/earth2.png",
    "id_portForm-4-image_desc": "Client Work",
    "id_portForm-4-item_title": "Fictional Earth",
    "id_portForm-4-desc": "A 3d model of Earth made and rendered in Blender.",
    "id_reviewForm-TOTAL_FORMS": "5",
    "id_reviewForm-INITIAL_FORMS": "0",
    "id_reviewForm-MIN_NUM_FORMS": "0",
    "id_reviewForm-MAX_NUM_FORMS": "1000",
    "id_reviewForm-0-comment": "I worked with Priyanshu on a project, and I must say, I was impressed by his skills and professionalism. He delivered outstanding results and exceeded my expectations.",
    "id_reviewForm-0-image": "C:/fakepath/girl.png",
    "id_reviewForm-0-name": "Sara Jones",
    "id_reviewForm-1-comment": "I attended one of Priyanshu's workshops, and it was one of the best learning experiences I've had. He made the material easy to understand and provided practical examples that I could apply in my work.",
    "id_reviewForm-1-image": "C:/fakepath/gamer.png",
    "id_reviewForm-1-name": "Johnson Smith",
    "id_reviewForm-2-comment": "I hired Priyanshu Mishra to create a marketing campaign for my business, and he did an excellent job. He understood my needs and goals, and the results were fantastic.",
    "id_reviewForm-2-image": "C:/fakepath/programmer.png",
    "id_reviewForm-2-name": "Ricky Clark",
    "id_reviewForm-3-comment": "I've known Priyanshu Mishra for years, and I can say that he is one of the most talented and dedicated professionals I've ever met. He always goes above and beyond to deliver exceptional work.",
    "id_reviewForm-3-image": "C:/fakepath/hacker.png",
    "id_reviewForm-3-name": "Trafalgar Law",
    "id_reviewForm-4-comment": "I attended Priyanshu's presentation at a conference, and it was outstanding. He was engaging, informative, and provided practical insights that I could apply in my work immediately.",
    "id_reviewForm-4-image": "C:/fakepath/woman.png",
    "id_reviewForm-4-name": "Ellie Joe"
}'''
print(json.loads(a))