# Generated by Django 4.1.7 on 2023-03-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('logo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('about', models.CharField(max_length=300)),
                ('work_title', models.CharField(max_length=300)),
                ('work_desc', models.CharField(max_length=300)),
                ('experience_years', models.CharField(max_length=300)),
                ('skill_1_title', models.CharField(max_length=300)),
                ('skill_1_desc', models.CharField(max_length=300)),
                ('skill_2_title', models.CharField(max_length=300)),
                ('skill_2_desc', models.CharField(max_length=300)),
                ('skill_3_title', models.CharField(max_length=300)),
                ('skill_3_desc', models.CharField(max_length=300)),
                ('skill_4_title', models.CharField(max_length=300)),
                ('skill_4_desc', models.CharField(max_length=300)),
                ('talent_1_title', models.CharField(max_length=300)),
                ('talent_1_perc', models.IntegerField()),
                ('talent_2_title', models.CharField(max_length=300)),
                ('talent_2_perc', models.IntegerField()),
                ('talent_3_title', models.CharField(max_length=300)),
                ('talent_3_perc', models.IntegerField()),
                ('age', models.IntegerField()),
                ('insta_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('desc_1', models.CharField(max_length=1000)),
                ('desc_2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_desc', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.about')),
            ],
        ),
    ]
