# Generated by Django 4.1.7 on 2023-03-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='about_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.about'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.FileField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.FileField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
