# Generated by Django 4.1.7 on 2023-03-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_event_about_id_portfolioitem_about_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_title',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='title',
            new_name='item_title',
        ),
    ]
