# Generated by Django 4.1.7 on 2023-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_about_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='about_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='about_id',
            field=models.CharField(max_length=10),
        ),
    ]
